language: node_js
node_js:
  - 12.6.0
before_script:
  - npm install @11ty/eleventy -g
script: eleventy --pathprefix="/"
branches:
  only:
  - dev
deploy:
  - provider: pages
    token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    edge: true
    local_dir: _site
    target_branch: master
    on:
      branch: dev