language: node_js
node_js:
  - 12.6.0
before_script:
  - npm install @11ty/eleventy -g
script: eleventy --pathprefix="/gboi/"
branches:
  only:
  - dev
deploy:
  local_dir: _site
  provider: pages:git
  token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  edge: true
  cleanup: true
  target_branch: master